package com.example.android2.model

const val REQUEST_API_KEY = "26ff853f727e23e10cff2660c284b698"
const val FILM_LIST_INTENT_FILTER = "FILM LIST INTENT FILTER"
const val DETAILS_LOAD_RESULT_EXTRA = "LOAD RESULT"
const val DETAILS_INTENT_EMPTY_EXTRA = "INTENT IS EMPTY"
const val DETAILS_DATA_EMPTY_EXTRA = "DATA IS EMPTY"
const val DETAILS_RESPONSE_EMPTY_EXTRA = "RESPONSE IS EMPTY"
const val DETAILS_REQUEST_ERROR_EXTRA = "REQUEST ERROR"
const val DETAILS_REQUEST_ERROR_MESSAGE_EXTRA = "REQUEST ERROR MESSAGE"
const val DETAILS_URL_MALFORMED_EXTRA = "URL MALFORMED"
const val DETAILS_RESPONSE_SUCCESS_EXTRA = "RESPONSE SUCCESS"
const val DETAILS_TITLE_EXTRA = "TITLE"
const val DETAILS_OVERVIEW_EXTRA = "OVERVIEW"

const val DETAILS_RATE_EXTRA = 0.0


const val TEMP_INVALID = "0"
const val FEELS_LIKE_INVALID = "0"
const val PROCESS_ERROR = "Обработка ошибки"