package com.example.android2.model

const val MOVIE_INTENT_FILTER = "MOVIE INTENT FILTER"
const val MOVIES_LIST_INTENT_FILTER = "MOVIES LIST INTENT FILTER"

const val DETAILS_LOAD_RESULT_EXTRA = "LOAD RESULT"
const val DETAILS_INTENT_EMPTY_EXTRA = "INTENT IS EMPTY"
const val DETAILS_DATA_EMPTY_EXTRA = "DATA IS EMPTY"
const val DETAILS_RESPONSE_EMPTY_EXTRA = "RESPONSE IS EMPTY"
const val DETAILS_REQUEST_ERROR_EXTRA = "REQUEST ERROR"
const val DETAILS_REQUEST_ERROR_MESSAGE_EXTRA = "REQUEST ERROR MESSAGE"
const val DETAILS_URL_MALFORMED_EXTRA = "URL MALFORMED"
const val DETAILS_RESPONSE_SUCCESS_EXTRA = "RESPONSE SUCCESS"
const val LIST_RESPONSE_SUCCESS_EXTRA = "LIST RESPONSE SUCCESS"

const val DETAILS_TITLE_EXTRA = "TITLE"
const val DETAILS_RATING_EXTRA = "RATING"
const val DETAILS_YEAR_EXTRA = "YEAR"
const val DETAILS_COUNTRIES_EXTRA = "COUNTRIES"
const val DETAILS_GENRES_EXTRA = "GENRES"
const val DETAILS_OVERVIEW_EXTRA = "OVERVIEW"
const val DETAILS_IMAGE_EXTRA = "IMAGE"

const val FILM_LIST_EXTRA = "LIST OF FILMS"
